# This file is copied to spec/ when you run 'rails generate rspec:install'
require 'spec_helper'
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
# Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }

# Checks for pending migrations and applies them before tests are run.
# If you are not using ActiveRecord, you can remove these lines.
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # You can uncomment this line to turn off ActiveRecord support entirely.
  # config.use_active_record = false

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, type: :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://relishapp.com/rspec/rspec-rails/docs
  config.infer_spec_type_from_file_location!

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")
end
# ===============================================
# ===============================================
# ===============================================

# template-app/spec/spec_helper.rb

# Protected Area Start
require 'simplecov'
SimpleCov.start 'rails' do
  add_filter '/vendor/'
  add_filter '/config/'
  add_filter '/migrate/'
  add_filter '/factories/'
  track_files 'bx/**/*.rb'
  add_group 'bx', %r{bx/}
  add_group "bx_block_admin", "bx/bx_block_admin/app/admin"

  track_files 'bx/bx_block_admin/app/admin/**/*.rb'
end

ENV['RAILS_ENV'] ||= 'test'

# Set which rails application (client_app or block) will be loaded by default
ENV['RSPEC_APP_SOURCE'] = 'client_app'

# Load client app helpers
$LOAD_PATH.unshift(File.expand_path('.', __dir__))

# Require client app swagger helper configuration
if File.exist?(Rails.root.join('spec', 'swagger_helper.rb'))
  require Rails.root.join('spec', 'swagger_helper.rb')
end
# Protected Area End

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.include Devise::Test::ControllerHelpers, type: :controller
  config.include Rails.application.routes.url_helpers
  config.include Warden::Test::Helpers

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

# Protected Area Start
# Configuration for Blocks specs 
RSpec.configure do |config|
  config.before(:each) do |example|
    # Detect the current engine based on the running spec file paths
    running_specs = example.metadata[:file_path]

    # Detect the source engine if it is rswag specs
    if running_specs.include?("example_group_helpers.rb")
      running_specs = example.metadata[:example_group][:absolute_file_path]
    end

    # Get the actual running spec file (not the helper)
    engine_match = running_specs.match(%r{bx/([^/]+)/spec}) if running_specs

    if engine_match
      engine_name = engine_match[1]
      engine_spec_path = Rails.root.join("bx", engine_name, "spec")
      engine_support_path = engine_spec_path.join("support")

      # Resetting requires and reloading FactoryBot setup (for each file)
      @last_running_spec ||= nil
      if @last_running_spec != running_specs
        @last_running_spec = running_specs
        # Reset require list to remove previously loaded helpers and factory_bot files
        $LOADED_FEATURES.reject! do |file|
          file.match?(%r{/bx/[^/]+/spec/}) && (  # Ensure file is inside bx/.../spec/
            file.end_with?("rails_helper.rb") ||
            file.end_with?("support/unit/factory_bot.rb")
          ) ||
          file.include?("/factories")  # Match any factories-related file
        end

        if defined?(FactoryBot)
          FactoryBot.factories.clear 
          FactoryBot.reload
        end

        # Reload the current engine’s helpers
        rails_helper_path = engine_spec_path.join("rails_helper.rb")
        factory_bot_path = engine_support_path.join("unit/factory_bot.rb")
        
        load rails_helper_path if File.exist?(rails_helper_path)
        # Reload FactoryBot setup and dependencies for this engine
        if File.exist?(factory_bot_path)
          load factory_bot_path
        end
      end
    end
  end
end
# Protected Area End

# ===============================================

# frozen_string_literal: true
require 'rails_helper'
include Warden::Test::Helpers

RSpec.describe Admin::BroadcastersController, type: :controller do
  render_views

  let(:admin_user) do 
    AdminUser.create!(
      name: "admin",
      email: "adminadmin@example.com",
      password: "Password1!!",
      password_confirmation: "Password1!!",
      user_type: "admin",
      activated: true
    )
  end

  let(:valid_attributes) { 
    {
      user_name: "Test Broadcaster",
      email: "broadcaster#{SecureRandom.hex(4)}@example.com",
      server_hostname: "localhost",
      server_port: 8000,
      server_password: "password123",
      server_mount: "/test",
      server_bitrate: 128
    }
  }

  let(:invalid_attributes) do
    {
      user_name: "",
      email: "",
      server_hostname: "",
      server_port: "",
      server_password: "",
      server_mount: "",
      server_bitrate: ""
    }
  end

  before(:each) do
    sign_in admin_user
  end

  before do
    allow(Broadcasters).to receive(:page_registered?).and_return(false)
    allow(Broadcasters).to receive(:is_being_loaded_from_app?).and_return(false)
  end

  it "does not call unload_activeadmin_resource when page is not registered" do
    expect(Broadcasters).not_to receive(:unload_activeadmin_resource)
    load Rails.root.join("bx/bx_block_admin/app/admin/broadcasters.rb")
  end

  context "when the page is registered and being loaded from app" do
    before do
      allow(Broadcasters).to receive(:page_registered?).with("Broadcaster").and_return(true)
      allow(Broadcasters).to receive(:is_being_loaded_from_app?).and_return(true)
    end

    it "calls unload_activeadmin_resource" do
      expect(Broadcasters).to receive(:unload_activeadmin_resource).with("Broadcaster")
      load Rails.root.join("bx/bx_block_admin/app/admin/broadcasters.rb")
    end
  end

  describe "GET /admin/broadcasters/new" do
    it "renders the new broadcaster form with server details section" do
      get :new
      
      expect(response).to be_successful
      expect(response.body).to include("Broadcaster Details")
      expect(response.body).to include("User Name")
      expect(response.body).to include("Email")
  
      # Only check for server details if admin is signed in
      expect(response.body).to include("Server hostname")
      expect(response.body).to include("Server port")
      expect(response.body).to include("Server password")
      expect(response.body).to include("Server mount")
      expect(response.body).to include("Server bitrate")
    end
  end

  describe 'POST #create' do
    context 'with valid attributes' do
      it 'creates a new Broadcaster and redirects' do
        expect {
          post :create, params: { account: valid_attributes }
        }.to change(AccountBlock::Account, :count).by(1)

        expect(response).to redirect_to(admin_broadcaster_path(AccountBlock::Account.last))
        expect(flash[:notice]).to eq("Broadcaster account created successfully. A password reset link has been sent to the email.")
      end

      it 'sets the correct user_type and activated values' do
        post :create, params: { account: valid_attributes }
        broadcaster = AccountBlock::Account.last

        expect(broadcaster.user_type).to eq("Broadcaster")
        expect(broadcaster.activated).to be_falsey
      end
    end

    context 'with invalid attributes' do
      it 'does not create a new Broadcaster and renders the new form' do
        expect {
          post :create, params: { account: invalid_attributes }
        }.not_to change(AccountBlock::Account, :count)

        expect(response).to render_template(:new)
        expect(response.body).to include("error")
      end
    end

    it 'permits the expected parameters' do
      expect(controller).to receive(:permitted_params).and_call_original
      post :create, params: { account: valid_attributes }
    end
    
  end
end

# ===============================================
# template-app/bx/bx_block_admin/spec/admin/admin_users_spec.rb
# frozen_string_literal: true
require_relative '../rails_helper'
include Warden::Test::Helpers

RSpec.describe Admin::AdminUsersController, type: :controller do
  render_views
  let(:admin_user) do 
    AdminUser.create!(
      name: "admin",
      email: "adminadmin@example.com",
      password: "Password1!!",
      password_confirmation: "Password1!!",
      user_type: "admin",
      activated: true
    )
  end

  let(:valid_attributes) { 
    {
      name: "Test Admin",
      email: "admin#{SecureRandom.hex(4)}@example.com",
      password: "Password1!!",
      password_confirmation: "Password1!!",
      user_type: "admin",
      activated: true
    }
  }

  let(:invalid_attributes) do
    {
      name: "",
      email: "",
      password: "",
      password_confirmation: "",
      user_type: "",
      activated: ""
    }
  end

  before(:each) do
    sign_in admin_user
  end

  before do
    # Clear any previous registration states to avoid conflicts
    allow(AdminUsers).to receive(:page_registered?).and_return(false)
    allow(AdminUsers).to receive(:is_being_loaded_from_app?).and_return(false)
  end

  it "does not call unload_activeadmin_resource when page is not registered" do
    expect(AdminUsers).not_to receive(:unload_activeadmin_resource)
    load Rails.root.join("bx/bx_block_admin/app/admin/admin_users.rb")
  end

  context "when the page is registered and being loaded from app" do
    before do
      allow(AdminUsers).to receive(:page_registered?).with("AdminUser").and_return(true)
      allow(AdminUsers).to receive(:is_being_loaded_from_app?).and_return(true)
    end

    it "calls unload_activeadmin_resource" do
      expect(AdminUsers).to receive(:unload_activeadmin_resource).with("AdminUser")
      load Rails.root.join("bx/bx_block_admin/app/admin/admin_users.rb")
    end
  end
    
  describe "GET /admin/admin_users/new" do
    it "renders the new form" do
      get :new
      expect(response).to be_successful
      expect(response.body).to include("Name")
      expect(response.body).to include("Email")
      expect(response.body).to include("Password")
      expect(response.body).to include("Password confirmation")
    end
  end

  describe 'POST #create' do
    let(:valid_params) do
      {
        admin_user: {
          name: "New Admin",
          email: "newadmin#{SecureRandom.hex(4)}@example.com",
          password: "Password1!!",
          password_confirmation: "Password1!!",
          user_type: "admin",
          activated: true
        }
      }
    end

    let(:invalid_params) do
      {
        admin_user: {
          name: "",
          email: "",
          password: "",
          password_confirmation: "",
          user_type: "",
          activated: ""
        }
      }
    end

    before do
      allow(BuilderBase::AnalyticsEvent).to receive(:publish)
    end

    context 'with valid parameters' do
      it 'creates a new AdminUser and redirects to the show page' do
        expect {
          post :create, params: valid_params
        }.to change(AdminUser, :count).by(1)

        expect(response).to redirect_to(admin_admin_user_path(AdminUser.last))
      end

      it 'calls publish_analytics_event with correct data' do
        expect_any_instance_of(Admin::AdminUsersController).to receive(:publish_analytics_event)
          .with('admin.account.created', hash_including(:name, :email, :user_type, :activated))

        post :create, params: valid_params
      end

      it 'publishes analytics event with expected data' do
        post :create, params: valid_params

        expect(BuilderBase::AnalyticsEvent).to have_received(:publish).with(
          hash_including(
            event_name: 'admin.account.created',
            properties: hash_including(
              "name" => "New Admin",
              "email" => a_string_starting_with("newadmin"),
              "user_type" => "admin",
              "activated" => "true",
              "action_by" => admin_user.id.to_s,
              "account_id" => a_string_matching(/\d+/)
            )
          )
        )
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new AdminUser and renders the new form' do
        expect {
          post :create, params: invalid_params
        }.not_to change(AdminUser, :count)

        expect(response).to render_template(:new)
        expect(response.body).to include("error")
      end

      it 'does not call publish_analytics_event' do
        expect_any_instance_of(Admin::AdminUsersController).not_to receive(:publish_analytics_event)
        post :create, params: invalid_params
      end
    end
  end

  describe 'PUT #update' do
    let!(:admin) { create(:admin_user) }
    let(:valid_params) { { id: admin.id, admin_user: { name: 'Updated', activated: false } } }
    let(:invalid_params) { { id: admin.id, admin_user: { name: '' } } }

    before do
      allow(BuilderBase::AnalyticsEvent).to receive(:publish)
    end

    context 'successful update' do
      it 'updates attributes' do
        put :update, params: valid_params
        expect(admin.reload.name).to eq('Updated')
      end

      it 'publishes analytics event' do
        put :update, params: valid_params
        expect(BuilderBase::AnalyticsEvent).to have_received(:publish)
          .with(hash_including(event_name: 'admin.account.updated'))
      end
    end

    context 'failed update' do
      it 'shows errors' do
        put :update, params: invalid_params
        expect(response).to render_template(:edit)
        expect(flash[:alert]).to be_present
      end
    end
  end
end
# ===============================================
# ===============================================
# ===============================================
# ===============================================# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================
# ===============================================